events {}

http {

  upstream static_backend {
    server static1:80;
    server static2:80;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://frontend:80;
    }

    location /api/ {
      proxy_pass http://api:5001/;
    }

    location /admin/ {
      proxy_pass http://admin:5002/;
    }

    location /static/ {
      proxy_pass http://static_backend/;
    }
  }
}
	

